### ISSUE TITLE
Add "wake time" graph

### ISSUE THREAD

**Issue by RomanHauksson** [vmiklos/plees-tracker#268] opened 2022-04-01 15:20 UTC
Just like the "start time" graph, but for end/wake times. Would you mind if I made a pull request for this? Just wanted to ask ahead of time.

**Comment by vmiklos** [comment] 2022-04-01 17:02
Yes, you're welcome to submit a PR for this. :-)

**Comment by vmiklos** [comment] 2023-05-12 08:33
Sorry, I just noticed this is a duplicate of #358, which I did in v7.5.3.

**Closed by vmiklos** 2023-05-12 08:33 UTC
Labels: enhancement, up for grabs
