### ISSUE TITLE
Export to calendar crashes

### ISSUE THREAD

**Issue by ghost** [vmiklos/plees-tracker#56] opened 2020-11-11 13:48 UTC
**Reproducer steps**
1. Click: Settings -> Export to Calendar
2. Select calendar 
3. Click confirm button (Select)

**Actual result**
App crashes

**Expected behavior**
App wont crash, and starts to synchronize sleeps into selected calendar

----------

The feature was implemented in this issue: https://github.com/vmiklos/plees-tracker/issues/41

**Comment by vmiklos** [comment] 2020-11-11 14:00
Can you provide an 'adb logcat' output to see what's the stacktrace?

**Comment by petrhejna** [comment] 2020-11-12 01:54
Uff, I have never sone that. Is there any guide you can recommand how to execute that?

**Comment by vmiklos** [comment] 2020-11-12 08:41
Please google for "adb logcat stacktrace howto" and pick your favorite hit. Let me know if that doesn't lead anywhere.

**Comment by ed-george** [comment] 2020-11-14 12:03
Watching this issue - @petrhejna are you able to provide details on the device you used when this crashed? I am happy to take a look at this @vmiklos when more info is provided

**Comment by petrhejna** [comment] 2020-11-14 13:23
I have it it mind, I hope I'll find time to debug it this weekend. But cant promise.

**Comment by petrhejna** [comment] 2020-11-14 23:40
```
11-15 00:39:32.612 16828 16871 E DatabaseUtils: java.lang.SecurityException: Permission Denial: writing com.android.providers.calendar.CalendarProvider2 uri content://com.android.calendar/events from pid=16848, uid=10089 requires android.permission.WRITE_CALENDAR, or grantUriPermission()
11-15 00:39:32.612 16828 16871 E DatabaseUtils: 	at android.content.ContentProvider.enforceWritePermissionInner(ContentProvider.java:709)
11-15 00:39:32.612 16828 16871 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceWritePermission(ContentProvider.java:518)
11-15 00:39:32.612 16828 16871 E DatabaseUtils: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:262)
11-15 00:39:32.612 16828 16871 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:152)
11-15 00:39:32.612 16828 16871 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:731)
11-15 00:39:32.637 16848 16848 E AndroidRuntime: FATAL EXCEPTION: main
11-15 00:39:32.637 16848 16848 E AndroidRuntime: Process: hu.vmiklos.plees_tracker, PID: 16848

**Comment by petrhejna** [comment] 2020-11-14 23:42
Permissions for Calendar are granted for the app.

**Comment by ed-george** [comment] 2020-11-15 16:17
@petrhejna Are you able to let us know what device and version of Android you are using? 

You can find this information in the Settings of the phone :)

**Comment by petrhejna** [comment] 2020-11-15 21:24
One Plus 7 Pro, LineageOS 16.0, Android 9

**Comment by petrhejna** [comment] 2020-11-15 21:24
Degooglified, no google services.

**Comment by petrhejna** [comment] 2020-12-08 07:23
@ed-george @vmiklos is there anything more I can provide to help to solve the issus?

**Comment by vmiklos** [comment] 2020-12-08 08:40
Easiest if @ed-george takes a look; failing that, I might look into this (get this working under the emulator, which perhaps matches your use-case) after https://github.com/vmiklos/plees-tracker/issues/32

In the meantime, of course you can investigate yourself, we're all developers after all. :)

**Comment by ed-george** [comment] 2020-12-08 09:55
Hi @petrhejna @vmiklos - apologies for the radio silence. I think the difficulty here is your particular OS choice and device setup might be a contributing factor and I have not seen this particular issue on stock Android 9 devices.

I will hopefully find some time to check this out properly by the end of the month, but I doubt I will have much capacity to check any sooner. @vmiklos if you want to take a look, by all means do - I suspect we might need to ensure the user is asked for 'write' permissions on calendars by default

**Comment by vmiklos** [comment] 2022-01-02 20:17
I can't reproduce this even on stock Android 11. Nothing happened in a year, let's close this for now.

**Closed by vmiklos** 2022-01-02 20:17 UTC
Labels: needinfo
