### ISSUE TITLE
Can't create Sleep the morning after

### ISSUE THREAD

**Issue by EdMaxPrime** [vmiklos/plees-tracker#262] opened 2022-03-04 20:53 UTC
**Reproducer steps**
1. Press start button
2. Press stop button a few seconds later
3. Click on the sleep in the list to open the edit menu
4. Edit the *start* time to 2:00 AM the same day
5. Edit the *end* time to 11:30 AM the same day

**Actual result**
Popup: "Not updating the sleep, stop is not after start". When you leave the menu, the sleep is recorded lasting a few seconds, none of the times are saved.

**Expected behavior**
For the times to be saved properly, resulting in the correct duration. This has worked before, but has stopped after the recent update.

**Comment by vmiklos** [comment] 2022-03-04 21:46
Is this a duplicate of https://github.com/vmiklos/plees-tracker/issues/253 ?

I just cut the v7.3.1 release, if you are on 7.3.0, then either use the debug apk from that issue or wait a bit till fdroid catches up.

**Comment by EdMaxPrime** [comment] 2022-03-04 21:54
Ah, I only looked through the open issues. Thanks @vmiklos , I'll wait for F-droid to catch up

**Comment by sslater11** [comment] 2022-03-09 06:25
Another solution for this is to change the time twice in a row.

After changing the date and time, you'll see it change in the app, click that time  and you'll see the time selector displaying the original time, so set it again and that works for me :).

Lol I was gonna post a bug report myself and looked at the code.

**Comment by vmiklos** [comment] 2022-03-09 06:53
Fine, closing this in that case.

**Closed by vmiklos** 2022-03-09 06:53 UTC
Labels: needinfo
